.mocharc.json, package-lock.json, package.json, src/SearchIndex.ts, src/index.ts, tests/sync.test.ts, tests/test_data/state-1/bi-connector-v1.json, tests/test_data/state-1/bi-connector-v2.json, tests/test_data/state-1/manual.json, tests/test_data/state-2/bi-connector-v2.json, tests/test_data/state-2/charts.json, tests/test_data/state-2/manual.json
This also includes a refactor to make testing easier, mainly moving `SearchIndex` to its own file.
The test contains two states, and tests transitioning the database from state 1 to state 2, and back to state 1 again. Tested mutations:
* Added properties (state 2 contains `charts.json`)
* Added documents (state 2 contains `tutorial/second-tutorial/index.html`)
* Removed properties (state 1->2 removes `bi-connector-v1`)
* Removed documents (state 2->1 removes `tutorial/second-tutorial/index.html`)
* Mutated documents (state 1->2 fixes a typo in `manual.json`: `s/Ap/App`)
=> DOP-1115: Add test to verify that database synchronization works

build/index.js, src/index.ts, tests/server.test.ts
Also removes deprecated node API.
=> Don't throw when handling a bad origin in checkAllowedOrigin()

build/SearchIndex.js, src/SearchIndex.ts
This adds the searchProperty field to the projection shown from docs-search-transport.
=> Add searchProperty to projection

build/Query.js, src/Query.ts, src/SearchIndex.ts
[Jira Ticket](https://jira.mongodb.org/browse/DOP-3368) Properties that still build with the legacy tooling use mut-0.9.x to generate their search manifests (from the built HTML rather than from the parser-generated AST). Since we would still like non-Snooty-deployed sites to be included in search, this PR restores the `text` field in query construction in docs-search-transport and makes the `code` and `paragraphs` fields optional
=> DOP-3368: restore support for legacy-style manifests

.drone.yml, environments/staging.yml
Ticket: DOP-3441
Updated Kanopy memory limits and requests to a more accurate allowance.
Kanopy team has decreed that all helm-chart apps must upgrade to at least v4.12.0 because of a breaking change going forward with k8 1.22 API deprecations. Slack message can [be found here](https://mongodb.slack.com/archives/CCKCR28BH/p1660591811877929).
Breaking this into two PRs to ensure safety of prod api
=> DOP-3441-Staging: Updated Kanopy memory limits and upgraded helm-chart 4.7.3 to 4.12.0

.drone.yml, environments/prod.yml
Ticket: [DOP-3441](https://jira.mongodb.org/browse/DOP-3441)
Updated memory limits and requests before Kanopy team sets mandatory amounts. Decided to go higher for safety's sake and further investigation of Kanopy's grafana charts over the past six months.
Upgraded `helm-chart` version of prod primarily. However, also upgraded staging to the latest version after speaking with Staff Infra Engineer. This upgrade is necessary for newer releases to follow [k8's 1.22 API scheduled deprecation](https://mongodb.slack.com/archives/CCKCR28BH/p1660591811877929).
Before merging but after approval, I will use the `mapkubeapis` Helm plugin to update deprecated and removed API versions in-place which is required for a successful build with the new `helm-chart` upgrade. The steps and reasonings can be …
=> DOP-3441-prod: Upgraded chart versions to 4.12.3, memory limits and requests for prod

src/Query.ts
DOP-3458
Adds a `tracking` field to enable query analytics.
=> DOP-3458: Add query analytics field

Dockerfile, environments/staging.yml
Increase [node process memory allocation ](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) to avoid error in ticket.
will follow up with a ticket to identify the area of memory leak and revert this fix
=> DOP-3585: allocate memory for node process. default back to 512 after fix

Dockerfile, environments/staging.yml, src/SearchIndex.ts
Allow empty string value for slug, based on DOP-3545
- reverts [previous fix](https://github.com/mongodb/docs-search-transport/pull/31) for increasing memory allocation for node process
- based on [this error](https://mongodb.splunkcloud.com/en-US/app/search/show_source?sid=1679578304.2371746&offset=0&latest_time=) for 
```
[2023-03-23 08:01:11] (error) AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
assert_1.default.ok(document.slug)
at /app/build/SearchIndex.js:284:22
```
=> DOP-3585: allow empty slug when composing upserts

build/SearchIndex.js
[latest logs](https://mongodb.splunkcloud.com/en-US/app/search/show_source?sid=1679597830.2420111&offset=49&latest_time=) were showing that [this change](https://github.com/mongodb/docs-search-transport/pull/32) didn't propogate. resultant of build files not being updated. ran `npx prettier --write .` after tsc as per node scripts
=> DOP-3585: commit build file

package.json
from drone build logs: https://drone.corp.mongodb.com/mongodb/docs-search-transport/75/1/2
```
Step 8/14 : RUN npm run build
---> Running in 37844b994578
> search-transport@0.1.0 build /app
> rm -r build; tsc && npm run format
rm: can't remove 'build': No such file or directory
sh: tsc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! search-transport@0.1.0 build: `rm -r build; tsc && npm run format`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the search-transport@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-04-10T21_30_02_066Z-debug.log
The command '/bin/sh -c …
```
=> Fix build step: include force flag for removing build dir

.dockerignore, Dockerfile, package.json
from this build log:
https://drone.corp.mongodb.com/mongodb/docs-search-transport/76/1/2
```
> search-transport@0.1.0 build /app
> rm -rf build; tsc && npm run format
sh: tsc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! search-transport@0.1.0 build: `rm -rf build; tsc && npm run format`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the search-transport@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
since we install with npm ci --production
=> DOP-3596: include tsc as part of prod dependencies

.github/workflows/test.yml, tests/integration/search.test.ts, tests/integration/server.test.ts, tests/integration/sync.test.ts
Two changes broke the unit tests:
- search transport server now instantiates after loading in the manifests (as well as search index update)
- search index requires a `Taxonomy` object when loading (required for query parsing)
=> update tests based on changes to search index server

.drone.yml, src/Query.ts, src/SearchIndex.ts, src/index.ts
Minor fix to not timeout on single letter queries.
[stage request responds with 400 but empty results ](https://docs-search-transport.docs.staging.corp.mongodb.com/search?q=a)
[prod request hangs with no response](https://docs-search-transport.mongodb.com/search?q=a)
=> DOP-3779: return 400 on single letter queries

environments/all.yml, environments/prod.yml, environments/staging.yml
We're actually using two different public/private keys for staging and prod users for Atlas Admin API
We were reference the same public key for both env
=> Environment fix: use different pub key for prod

src/data/atlas-search-index.ts
https://jira.mongodb.org/browse/DOP-3950
This change adds `''` as a stopword to prevent the custom whitespace analyzer being used for `$` prefixed cases from querying for empty strings.
=> DOP-3950: Add emptychar stopword to $ analyzer

src/data/atlas-search-index.ts
Hello!
Charles Burnett, our Atlas Search SA, told me our synonym file isn't working because the synonym analyzer needs to match index/query analyzers.  Previously our synonym analyzer was lucene.keyword, but we're using lucene.english for our query & index analyzers.  They both need to be lucene.english for the synonym file to take effect.  I've made that change with this pull request, which should solve the problem.
Thank you!
Sarah
=> Update synonym analyzer

src/Query/index.ts
`includeInGlobalSearch` flag should only be used if searchProperty is not passed
=> only require includeInGlobalSearch if searchProperty not specified

.drone.yml, src/Marian/index.ts, src/Query/index.ts, src/Query/util.ts, src/SearchIndex/index.ts, src/SearchIndex/types.ts, src/SearchIndex/util.ts, tests/resources/utils-data.ts, tests/unit/SearchIndex.test.ts
[Pre-req PR](https://github.com/mongodb/docs-search-transport/pull/76)
[JIRA](https://jira.mongodb.org/browse/DOP-4048)
**Goal**: This PR is intended to update the functionality and format of our `/v2/search/meta` route, as to match the new format of the `/v2/status` route. This allows for front end to have dynamic facets with a single API query to the aforementioned route with query parameters for filters ([example](https://docs-search-transport.docs.staging.corp.mongodb.com/v2/search/meta?q=atlas&facets.target_product=atlas))
**Description:**
- `/v2/search/meta` route has been updated from a trie structure of shallow level of taxonomy, to a list structure as described in DOP-4048 for all depths. Front end can decide to show/hide based off the route response, without any data …
=> DOP-4048: responsive facet responses

.drone.yml, src/SearchIndex/util.ts
[JIRA](https://jira.mongodb.org/browse/DOP-4075)
**Description:**  Were returning 500 errors when getting 0 results for metadata. When catching manually:
```
VM925:1 Uncaught TypeError: Cannot read properties of undefined (reading 'options')
at eval (eval at handleFacetValue (util.js:1:1), <anonymous>:1:15)
at handleFacetValue (util.js:36:17)
at convertToFacetOptions (util.js:91:17)
at Object.formatFacetMetaResponse (util.js:28:20)
at SearchIndex.fetchFacets (index.js:40:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Marian.handleMetaSearch (index.js:189:23)
```
This is happening because we are trying to recursively put child buckets into parent buckets that DNE. Added a skip to this function and successfully returning 0 results.
[Prod meta …
=> DOP-4075: fix meta results for 0 count

.drone.yml, src/Marian/index.ts, src/Query/index.ts, src/Query/util.ts, src/SearchIndex/index.ts, tests/integration/search.test.ts
[JIRA](https://jira.mongodb.org/browse/DOP-4071)
**Description:** PR provides an optional URL query param that allows users to dictate whether facets are combined using an OR/AND operator. Previously, all query params at different levels were treated as **AND** queries, and could therefore result in no results.
[Example of two filters passed and returning 0 results on prod.](https://docs-search-transport.mongodb.com/search?q=mongodb&facets.target_product=compass&facets.target_product%3Erealm%3Esub_product=web) Selected facets are `facets.target_product=compass` and `facets.target_product>realm>sub_product=web` but these are being treated as AND queries, and thus returning 0 results. ([see splunk log for aggregation query](https://mongodb.splunkcloud.com/en-US/app/search/show_source?sid=169 …
=> DOP-4071: allow either or/and for facet filters when performing search

.drone.yml, src/Query/index.ts, src/Query/util.ts, tests/integration/search.test.ts
[JIRA](https://jira.mongodb.org/browse/DOP-4065)
See second bullet point for A/C: `/search route returns documents with "facets" field`
This PR is intended to return the `document.facets` fields in a similar format as the [/v2/status response](https://docs-search-transport.docs.staging.corp.mongodb.com/v2/status), namely with facet values having `{key, id}` properties. This allows for front end to map this to an existing facet from the above response.
[Current search results do not return `facets` field](https://docs-search-transport.mongodb.com/search?q=meta)
[Staging branch returns `facets` field, along with all previous fields in the above example](https://docs-search-transport.docs.staging.corp.mongodb.com/search?q=meta)
=> DOP-4065: return search results' facets (in desired format)

.drone.yml, src/Query/util.ts
**Context:**
[Previous PR had introduced a way](https://github.com/mongodb/docs-search-transport/pull/82/files#diff-244d01de0824eda50531865572bc5dfaf1c3325fcb645aa6012177cfbdbb1017R145) of re-ordering search documents when "grouping" by unnested facet properties. To mitigate this issue, resorted to remove the unnesting and grouping, and doing the facet object formatting in the "projection" step.
Now, order is preserved from the $search step, and projection only changes each document's "facets" property.
[results ordered on prod](https://docs-search-transport.mongodb.com/search?q=create-atlas-account)
[test results order preserved on stage, with facets formatted](https://docs-search-transport.docs.staging.corp.mongodb.com/search?q=create-atlas-account) (some results may be missing only due …
=> DOP-4065: fix projection

src/Marian/index.ts, src/Query/index.ts, src/Query/util.ts, src/SearchIndex/index.ts
DOP-4089 discussions (on [slack](https://mongodb.slack.com/archives/GGPUBUMLN/p1698844414318519) and [tech spec](https://docs.google.com/document/d/1c9P5_wnlLswoZftJbZG-baqG1Fgs26lO1gv7ExgT3Ss/edit#heading=h.ytznsphw0fe2) included allowing same base level selections as "OR" statements, while treating selections of different base categories as "AND" statements.
This PR aims to do this, by combining query params of the **same base facet**, into a nested compound SHOULD operator, under the root MUST compound operator.
As an example:
Query route:
```
/search/ ?q=$and
&facets.genre=tutorial
&facets.target_product>atlas>sub_product=search
&facets.target_product=drivers
``` 
previously, this translated to MUST statements for each line. and thus, it would return 0 results, since all documents are …
=> DOP-4089: treat same level selections as "or"

src/Marian/index.ts, src/SearchIndex/index.ts, src/SearchIndex/types.ts, src/SearchIndex/util.ts, tests/integration/sync.test.ts, tests/integration/test_data/state-1/manual.json, tests/resources/utils-data.ts
DOP-4109
* Facets are generally ordered based on the following:
1) Facet option/category
2) Alphabetical order
* Facets with versions are ordered similarly to how the frontend currently does: from descending order, with "upcoming" or "latest" above "current" or "stable".
* Facets are ordered in a few places:
1) When creating the structured taxonomy response after index creation. This is the same object returned by `/v2/status`.
2) When upserting documents based on the manifest. This is to avoid needing to sort facets for every individual search result for every single search.
3) Whenever `/v2/search/meta?q=<query>` is called. This is sorted for every request/response. I'm unsure if there's a way to sort only once and forget it since it seems like facets are aggregated per request.
* …
=> DOP-4109: Sort facets based on desired UI order

.drone.yml, src/Marian/index.ts
DOP-3998
as per[ Kanopy documentation ](https://kanopy.corp.mongodb.com/docs/security/corpsecure/#cors-simple-requests)on CORS policies, this change allows server to accept credentials
tested with this [staged change](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/DOP-3998-2/search/?q=atlas&page=1).
Above staged site makes requests to `https://docs-search-transport.docs.staging.corp.mongodb.com` while sending user credentials via `request.header.cookies` (this is obtained via okta auth) to authenticate with server to bypass CORS issues
=> DOP-3998: allow CORS authentication

src/Query/index.ts
[DOP-4121](https://jira.mongodb.org/browse/DOP-4121)
Realm docs are currently overrepresented in search result sets by a slight margin. This PR buries results with the `searchProperty` `realm-master` but keeps all other results, as well as their order, identical. The approach used was the suggested one for burying/boosting certain results as detailed [here](https://docs.google.com/document/d/1G1RYHBbFXqm5kG98GETCTvKj1UJHv5rzDHG18X-5jYM/edit#heading=h.sq6vzuky8sas)
- Testing: Only a limited amount of testing could be done. To test, query results from the local staging instance were compared with the results of the same queries on the staging server. 
Ex: https://docs-search-transport.docs.staging.corp.mongodb.com/search/?q=sdk compared to http://localhost:8080/search/?q=sdk. Several …
=> DOP-4121: Boost/bury based on product usage & pageviews

src/Marian/index.ts, src/SearchIndex/index.ts
[DOP-4145](https://jira.mongodb.org/browse/DOP-4145)
Docs Search Transport [Splunk logs](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22docs-prod%22%20%20source%3D%22*search-transport*%22%20%5C(error%5C)&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1700024400&latest=1700715600&sid=1700685979.1211656) show several errors. The two that are the focus of this ticket are URL Type Errors and facet fetching errors. Examples of each are included below
Error handling and logging of such errors is now improved to provide greater context for debugging purposes
=> DOP-4145: Add context to Docs Search Transport errors

README.md, src/Marian/index.ts, src/Query/index.ts, src/Query/types.ts, src/SearchIndex/types.ts, src/SearchIndex/util.ts, src/index.ts
DOP-4182
I tried to update `any` types when it seemed pretty straightforward. Here are some places where I did not change types (as well as left a couple other comments detailing reasoning):
- [src/data/atlas-types.ts](https://github.com/mongodb/docs-search-transport/blob/main/src/data/atlas-types.ts#L9) - I couldn't really easily find enough information on the returned `SearchIndexResponse` to know what types should exist in `customAnalyzer`. 
- [src/Marian/index.ts](https://github.com/mongodb/docs-search-transport/blob/main/src/Marian/index.ts#L135) - don't feel it's necessary to type the error
- [src/SearchIndex/util.ts](https://github.com/mongodb/docs-search-transport/blob/main/src/SearchIndex/util.ts#L176) - not sure what the `any` in `Record<string,any>` would look like, figured at …
=> DOP-4182: Specify types for query builder in search transport

.drone.yml, environments/prod.yml, environments/staging.yml, sample.env, src/Marian/index.ts, src/SearchIndex/index.ts, src/index.ts, tests/integration/search.test.ts, tests/integration/server.test.ts, tests/integration/sync.test.ts
DOP-4489
This change opens up a new route `/manifests` that provides a link of JSON files that smartling's crawlers can access, for pre processing and translations.
- Previously, we were setting the full URI for the manifest s3 location, so added a few more env variables without changing the existing logic.
- This does not require any changes to the README but additional changes have been made to env variables (sample env, drone env variables)
=> DOP-4489: supply list of manifest files in S3

src/Marian/index.ts, src/Query/index.ts, tests/unit/Query.test.ts
DOP-4503
- See ticket for explanation of bug. [In the case shown in this log](https://mongodb.splunkcloud.com/en-US/app/search/show_source?sid=scheduler_cmF5bXVuZC5yb2RyaWd1ZXo__search__RMD5f5aaa11866325be7_at_1712116800_3520&offset=0&latest_time=), user is searching for `constructor` which exists as a property on the object, but does not exist in the constant mapping as a key. The fix here is to check that the property exists as a type of `String[]`
- Added this case as a unit test to prevent future errors of the same kind.
=> DOP-4503: check that property mapping is only checking for string properties

.drone.yml, src/Query/index.ts, src/Query/types.ts, tests/unit/Query.test.ts
DOP-3976
- Adds a [phrase](https://mongodb.com/docs/atlas/atlas-search/phrase/) operator to search across documents' `paragraphs` `headings` and `text` for the original search phrase with standard analyzer. Added a boost to this score as we would want documents with these words in order to be higher in the ranking
Can see the change here:
https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/search/?q=max+disk+iops&page=1
=> DOP-3976: add a boost for phrase of the original query

.drone.yml, src/Query/index.ts, src/Query/types.ts, src/Query/util.ts, tests/unit/Query.test.ts
DOP-4323
Add text matching on facet values. Also fixed a bug in which selected facets were being overwritten by the last facet in the list, as well as added a test to check that the amount of clauses created by `extractFacetFilters()` is the same as the amount of facets passed in through the URL.
Staging link at https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/search/
=> DOP-4323: Boost query matches on taxonomy values

.drone.yml, src/Query/index.ts, src/data/atlas-search-index.ts, tests/unit/Query.test.ts
DOP-3934
- Updates custom analyzer to a simple mapping vs regex token filter
- Also removes the [hard coded mapping](https://github.com/mongodb/docs-search-transport/blob/main/src/data/term-result-mappings.ts) from the query as this shouldn't be needed anymore
=> DOP-3934: update custom analyzer to escape $

src/Marian/index.ts, src/Query/index.ts, src/SearchIndex/index.ts, tests/integration/search.test.ts, tests/resources/utils-data.ts, tests/unit/Query.test.ts
DOP-4552 
I wanted to leverage the existing `getFacetKeys` function in Search Index, but obtaining the taxonomy and passing it into this function outside `AtlasAdmin` proved a bit cumbersome.
This solution is the main one that comes to mind, but open to any suggestions for better code structure or locally storing the facet key names into a member of `SearchIndex`, similar to [insertTaxonomyIntoSearchIndex](https://github.com/mongodb/docs-search-transport/blob/main/src/AtlasAdmin/index.ts#L155) but to my knowledge the results of this function are only being uploaded online and doesn't exist locally/in a way that's easily accessible to `Query`.
- - [x] This PR does not introduce changes …
=> DOP-4552: Get facet names programmatically in Query/index.ts

src/Marian/index.ts
[DOP-4593](https://jira.mongodb.org/browse/DOP-4593)
Smartling crawler can't follow links in a JSON array, but it can follow HTML links. This endpoint is only being used for Smartling's crawler so this PR converts the format of all manifest links to HTML
Sometimes the 'should properly handle incorrect urls in manifests' test passes and sometimes fails on the same code if I rerun jobs, I am not sure why/if it should be investigated more thoroughly.
- - [x] This PR does not introduce changes that should be reflected in the README
=> DOP-4593: Search endpoint to return HTML format for manifest list

src/Marian/index.ts
[DOP-4593](https://jira.mongodb.org/browse/DOP-4593)
After [DOP-4593](https://jira.mongodb.org/browse/DOP-4593) was merged, @rayangler caught that we're creating a new div instead of a closing div in the /manifests endpoint [here](https://github.com/mongodb/docs-search-transport/pull/109/files#diff-f709f66121d0b7c81d6292c1b7ed41bbfde1e20b075779bd9fe635162c86e431R338). This PR fixes it.
https://docs-search-transport-dev.docs.staging.corp.mongodb.com/manifests
- - [x] This PR does not introduce changes that should be reflected in the README
=> DOP-4593-b hotfix

environments/dev.yml, environments/staging.yml
Staging and dev instances of Docs Search Transport went offline due to memory limits based on [Splunk logs](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Ddocs-staging%20source%3D*docs-search-transport-dev-web-app-748f6fdcf8-9wbc2*&earliest=1718913259&latest=now&sid=1718916865.28759334&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf). This PR hopes to arbitrarily bump the resources on non-prod instances to 75% of prod instances. 
If this doesn't fix the issue, the backup plan is to bump resources up to match prod's.
- - [x] This PR does not introduce changes that should be reflected in the README
=> Bump resources for staging and dev instances to 75% of prod

src/SearchPropertyMapping/index.ts, src/SearchPropertyMapping/types.ts
DOP-5081
- This PR skips branches with property for `noIndexing` from being stored into search server's SearchPropertyMapping. This is used when users provide a query term without a project-version filter so that we only serve results from active branches (now updated to `active && !noIndexing`)
- [This function](https://services.cloud.mongodb.com/groups/5bad1d3d96e82129f16c5df3/apps/5d41ef5e2de84772fc7c2de2/functions/6279548c1fdab5262a3460c8) will also have to be updated (used to populate filters on the RHS of search page). I have a draft there that will be deployed at same time of search transport's deploy after the change.
- - [X] This PR does not introduce changes that should be …
=> DOP-5081: skip noIndexing branches from being stored into searchPropertyMapping

src/Query/index.ts, src/data/term-result-mappings.ts, tests/unit/Query.test.ts
[DOP-5566](https://jira.mongodb.org/browse/DOP-5566)
This gives more boost to earlier entries in the mapped results so as to respect the order given. If every entry is given the same boost, the ordering in result is not deterministic.
- - [x] This PR does not introduce changes that should be reflected in the README
=> (DOP-5566): Respect order in term-result-mappings.ts

tests/unit/Query.test.ts
DOP-5622 
- Follow up to DOP-5566. Updated the test to find one with a lower score, vs expecting the location of it, given other compounds in the query. (Also the values start at 110 and go up)
=> DOP-5622: fix failing test

src/Marian/index.ts, src/Query/index.ts
DOP-5316
**The problem:**
Splunk is logging too many errors and it's unclear why.
**The solution:**
* Added new error messages to `InvalidQuery` throws to make it more specific **why** a query is not being handled.
* Move the error log that Splunk kept picking up around such that it would only log as an error if it's truly unexpected. We should treat `InvalidQuery` errors as "expected" within the context of the application as we only throw them if the user input is bad. We'll still log a warning in case we need to track and debug them.
We'll see how effective this solution is at reducing Splunk error alerts over time after this is deployed to prod.
- - [x] This PR does not introduce …
=> DOP-5316: Only log error if unhandled

src/Marian/index.ts, src/Query/types.ts, src/SearchIndex/index.ts, tests/integration/search.test.ts
DOP-5578
This PR aims to store searched terms into a MDB collection in the search db.
- Tested this locally and was able to save to `search-test` DB under collection `query`
**Note:** unrelated test failing for the Search Index test. Possibly worth rewriting the test suite so we can operate on one set of data
=> DOP-5578: store user query in collection

package-lock.json, src/Marian/index.ts, src/Query/util.ts, src/SearchIndex/index.ts, src/data/term-result-mappings.ts, tests/integration/search.test.ts
DOP-5912
Per Sarah Lin's request, we'll add simple booleans to our search.query collection to help with query analytics.
`resultsFound` will be true if at least one result was returned to the user.
`appliedFilter` will be true if the user applied any filters to their search query.
This PR along with the creation of a script [in this PR](https://github.com/10gen/snooty-scripts/pull/36) will satisfy the entirety of DOP-5912 and give Sarah Lin the analytics she needs going forward.
To test: you can use staging. 
Staging link: 
https://docs-search-transport-dev.docs.staging.corp.mongodb.com/search/
This now creates the specified documents in the `search-staging.query` db collection
- - …
=> DOP-5912: Add `resultsFound` & `appliedFilter` booleans to db insertion
